version: "3.9"

services:
  backend:
    # image: form-backend
    build: ./backend
    container_name: form-backend
    restart: always
    networks:
      - form-network

  frontend:
    # image: form-frontend
    build: ./frontend
    container_name: form-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always
    networks:
      - form-network

networks:
  form-network:
    driver: bridge
